### ISSUE TITLE
Freeing PA4, PA5

### ISSUE THREAD

**Issue by pantonov2** [hobbymachinist/els#11]
First of course congrats on the great job well done!!

I'm considering this project for a small lathe where I'd add a spindle control via analog signal. What would be most effective way to free one DAC output where pin is currently in use for TFT data? Had some look at source where a comment stays stating that pin number is ignored...

Another approach would be to generate a PWM and convert it to voltage. I'm a little bit reluctant to do so when a DAC is there.

I'm also considering adding HW limits and getting rid of the overpriced keypad while reducing number of keys/buttons mostly because of space considerations.

Thanks in advance!

**Comment by hobbymachinist** [comment]
It would require a bit of a rewrite of the tft code and the reason to use contiguous pins is to reduce the bit operations in data transfer and thereby reduce refresh latency - this has an impact on time critical operations e.g. threading.

Feel free to experiment with it, my long term plan is to use pwm since I plan to replace the VFD with a servo drive. It might be easier to add an external i2c or spi dac, or even just use pwm with an appropriate low pass filter.

It is open source, modify the code and design as it suits you but I wouldn't be interested in merging any breaking changes upstream since this is mostly a worklog / archive of my setup that could be of use as a starting point for others.
